"""Utility helpers for assembling downloadable scan reports."""

import io
import math
from datetime import datetime
from typing import Iterable, Optional, Sequence

from django.utils import timezone
from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter
from reportlab.graphics.charts.barcharts import VerticalBarChart
from reportlab.graphics.shapes import Drawing
from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from xml.sax.saxutils import escape

REPORT_NAME = "DPDP Cloud Auditor"
REPORT_TITLE = "Cloud Security Scan Report"
THEME_BLUE = colors.HexColor("#1F4E79")
THEME_LIGHT = colors.HexColor("#EAF2F8")
ROW_LIGHT = colors.HexColor("#F7FAFC")
TEXT_DARK = colors.HexColor("#1F2937")
EXCEL_THEME_BLUE = "1F4E79"

SEVERITY_ORDER = [
    ("CRITICAL", "Critical"),
    ("HIGH", "High"),
    ("MEDIUM", "Medium"),
    ("LOW", "Low"),
]

SEVERITY_COLOR_MAP = {
    "CRITICAL": colors.HexColor("#D7263D"),
    "HIGH": colors.HexColor("#F18F01"),
    "MEDIUM": colors.HexColor("#F2C057"),
    "LOW": colors.HexColor("#2EC4B6"),
}

SEVERITY_TEXT_COLOR = {
    "CRITICAL": colors.white,
    "HIGH": colors.white,
    "MEDIUM": TEXT_DARK,
    "LOW": TEXT_DARK,
}

EXCEL_SEVERITY_COLOR = {
    "CRITICAL": "FFC4C4",
    "HIGH": "FFE2BA",
    "MEDIUM": "FFF4A3",
    "LOW": "D4F1E4",
}

THIN_SIDE = Side(style="thin", color="D9E2F2")
THIN_BORDER = Border(left=THIN_SIDE, right=THIN_SIDE, top=THIN_SIDE, bottom=THIN_SIDE)


def _normalise_sequence(value):
    if not value:
        return []
    if isinstance(value, str):
        return [value]
    return list(value)


def _format_datetime(value: Optional[datetime]) -> str:
    if not value:
        return "N/A"
    try:
        return value.strftime("%B %d, %Y %H:%M UTC")
    except (AttributeError, ValueError):
        return str(value)


def _make_paragraph(value: str, style) -> Paragraph:
    return Paragraph(escape(str(value)), style)


def _format_scan_date_range(scan_jobs: Sequence) -> str:
    dates = [
        (job.completed_at or job.started_at)
        for job in scan_jobs
        if getattr(job, "started_at", None) or getattr(job, "completed_at", None)
    ]
    if not dates:
        return "N/A"

    earliest = min(dates)
    latest = max(dates)
    if earliest == latest:
        return _format_datetime(earliest)

    return f"{_format_datetime(earliest)} – {_format_datetime(latest)}"


def _format_scan_reference(scan_jobs: Sequence) -> str:
    job_ids = [str(job.id) for job in scan_jobs if job]
    if not job_ids:
        return "N/A"

    value = f"#{job_ids[0]}"
    if len(job_ids) > 1:
        value = f"{value} (+{len(job_ids) - 1} more)"
    return value


def _format_scan_regions_summary(scan_regions: Sequence[str] | None) -> str:
    regions = _normalise_sequence(scan_regions)
    if not regions:
        return "N/A"

    if len(regions) <= 4:
        return ", ".join(regions)

    return f"{len(regions)} regions selected"


def _count_regions(scan_regions: Sequence[str] | None) -> int:
    return len(_normalise_sequence(scan_regions))


def _collect_compliance_observations(findings_list: Sequence) -> list[str]:
    flagged = []
    for finding in findings_list:
        combined_text = " ".join(
            [
                str(getattr(finding, "issue_type", "") or ""),
                str(getattr(finding, "description", "") or ""),
                str(getattr(finding, "recommendation", "") or ""),
                str(getattr(finding, "region", "") or ""),
            ]
        ).lower()

        if any(
            keyword in combined_text
            for keyword in ("india", "sensitive", "personal data", "dpdp", "residency")
        ):
            flagged.append(finding)

    if flagged:
        return [
            "One or more findings indicate that sensitive data or region placement may require additional compliance review."
        ]

    return [
        "No explicit compliance-related warning was generated by the current rule set."
    ]


def _build_severity_chart(severity_counts: dict) -> Optional[Drawing]:
    labels = [label for _, label in SEVERITY_ORDER]
    values = [severity_counts[key] for key, _ in SEVERITY_ORDER]

    if sum(values) == 0:
        return None

    max_value = max(values)
    chart_height = 110
    chart_width = 230

    chart = VerticalBarChart()
    chart.x = 10
    chart.y = 15
    chart.height = chart_height
    chart.width = chart_width
    chart.data = [values]
    chart.categoryAxis.categoryNames = labels
    chart.categoryAxis.labels.boxAnchor = "n"
    chart.categoryAxis.labels.angle = 0
    chart.categoryAxis.labels.dx = 0
    chart.valueAxis.valueMin = 0
    chart.valueAxis.valueMax = max_value + max(1, max_value // 5)
    chart.valueAxis.valueStep = max(1, math.ceil(chart.valueAxis.valueMax / 5))
    chart.barWidth = 18
    chart.barLabels.nudge = 5
    chart.barLabels.angle = 90
    chart.barLabels.fontSize = 7
    chart.barLabels.boxAnchor = "n"
    chart.barLabelFormat = "%d"
    chart.strokeColor = THEME_BLUE

    for index, (key, _) in enumerate(SEVERITY_ORDER):
        if index >= len(chart.bars):
            break
        chart.bars[index].fillColor = SEVERITY_COLOR_MAP.get(key, colors.grey)

    drawing = Drawing(chart_width + 40, chart_height + 40)
    drawing.add(chart)
    return drawing


def _draw_pdf_page(canvas, doc):
    page_width, page_height = doc.pagesize

    canvas.saveState()

    header_height = 0.55 * inch
    footer_y = 0.42 * inch

    canvas.setFillColor(THEME_BLUE)
    canvas.rect(
        0, page_height - header_height, page_width, header_height, stroke=0, fill=1
    )

    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 14)
    canvas.drawString(doc.leftMargin, page_height - 0.34 * inch, REPORT_NAME)

    canvas.setFont("Helvetica", 8.5)
    canvas.drawRightString(
        page_width - doc.rightMargin,
        page_height - 0.34 * inch,
        REPORT_TITLE,
    )

    canvas.setStrokeColor(THEME_BLUE)
    canvas.setLineWidth(0.6)
    canvas.line(
        doc.leftMargin,
        footer_y + 0.12 * inch,
        page_width - doc.rightMargin,
        footer_y + 0.12 * inch,
    )

    canvas.setFillColor(colors.HexColor("#6B7280"))
    canvas.setFont("Helvetica", 8)
    canvas.drawString(doc.leftMargin, footer_y - 0.02 * inch, REPORT_NAME)
    canvas.drawRightString(
        page_width - doc.rightMargin,
        footer_y - 0.02 * inch,
        f"Page {canvas.getPageNumber()}",
    )

    canvas.restoreState()


def _write_excel_banner(sheet, title: str, subtitle: str, end_col: int) -> None:
    sheet.merge_cells(start_row=1, start_column=1, end_row=1, end_column=end_col)
    sheet.merge_cells(start_row=2, start_column=1, end_row=2, end_column=end_col)

    title_cell = sheet.cell(row=1, column=1)
    subtitle_cell = sheet.cell(row=2, column=1)

    title_cell.value = title
    subtitle_cell.value = subtitle

    title_cell.font = Font(bold=True, color="FFFFFF", size=14)
    subtitle_cell.font = Font(bold=True, color=EXCEL_THEME_BLUE, size=11)

    title_cell.fill = PatternFill("solid", fgColor=EXCEL_THEME_BLUE)
    subtitle_cell.fill = PatternFill("solid", fgColor="D9EAF7")

    title_cell.alignment = Alignment(horizontal="center", vertical="center")
    subtitle_cell.alignment = Alignment(horizontal="center", vertical="center")

    sheet.row_dimensions[1].height = 22
    sheet.row_dimensions[2].height = 18
    sheet.sheet_view.showGridLines = False


def _auto_size_columns(
    sheet, start_row: int = 1, min_width: int = 12, max_width: int = 60
) -> None:
    for col_idx in range(1, sheet.max_column + 1):
        max_length = 0
        for row_idx in range(start_row, sheet.max_row + 1):
            value = sheet.cell(row=row_idx, column=col_idx).value
            if value is not None:
                max_length = max(max_length, len(str(value)))
        sheet.column_dimensions[get_column_letter(col_idx)].width = min(
            max(max_length + 2, min_width),
            max_width,
        )


def generate_pdf_report(
    findings: Iterable,
    report_context: dict,
    requested_by,
    scan_logs: Optional[Sequence] = None,
) -> io.BytesIO:
    buffer = io.BytesIO()
    findings_list = list(findings)

    doc = SimpleDocTemplate(
        buffer,
        pagesize=LETTER,
        rightMargin=inch * 0.4,
        leftMargin=inch * 0.4,
        topMargin=inch * 1.0,
        bottomMargin=inch * 0.65,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=20,
        textColor=THEME_BLUE,
        alignment=1,
        spaceAfter=4,
    )
    subtitle_style = ParagraphStyle(
        "ReportSubtitle",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=9.5,
        textColor=colors.HexColor("#6B7280"),
        alignment=1,
        spaceAfter=10,
    )
    section_style = ParagraphStyle(
        "SectionTitle",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=12.5,
        textColor=THEME_BLUE,
        spaceBefore=8,
        spaceAfter=6,
    )
    body_style = ParagraphStyle(
        "ReportBody",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=9.4,
        leading=12,
        spaceAfter=6,
    )
    table_body_style = ParagraphStyle(
        "TableBody",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=8.2,
        leading=9.5,
        spaceAfter=0,
    )
    table_header_style = ParagraphStyle(
        "TableHeader",
        parent=styles["BodyText"],
        fontName="Helvetica-Bold",
        fontSize=8.2,
        leading=9.5,
        spaceAfter=0,
        textColor=colors.white,
    )

    scan_job = report_context.get("scan_job")
    scan_jobs = report_context.get("scan_jobs") or ([scan_job] if scan_job else [])
    scan_jobs = [job for job in scan_jobs if job]
    total_findings = len(findings_list)
    severity_counts = {key: 0 for key, _ in SEVERITY_ORDER}

    for finding in findings_list:
        severity = getattr(finding, "severity", "").upper()
        if severity in severity_counts:
            severity_counts[severity] += 1

    generation_date = timezone.now()
    generation_date_text = _format_datetime(generation_date)
    scan_date_text = _format_scan_date_range(scan_jobs)
    scan_reference_text = _format_scan_reference(scan_jobs)

    if requested_by:
        requested_by_name = requested_by.get_full_name() or getattr(
            requested_by, "username", "N/A"
        )
        requested_by_email = getattr(requested_by, "email", "n/a") or "n/a"
    else:
        requested_by_name = "N/A"
        requested_by_email = "n/a"

    cloud_account = report_context.get("cloud_account") or getattr(
        scan_job, "cloud_account", None
    )
    provider = cloud_account.get_provider_display() if cloud_account else "N/A"
    account_name = cloud_account.account_name if cloud_account else "N/A"

    scan_regions = report_context.get("scan_regions")
    scan_regions_text = _format_scan_regions_summary(scan_regions)
    region_count = _count_regions(scan_regions)

    compliance_notes = _collect_compliance_observations(findings_list)

    flowables = [
        Paragraph(REPORT_TITLE, title_style),
        Paragraph(
            "Automated cloud security and compliance analysis for the selected environment.",
            subtitle_style,
        ),
        Paragraph("Report Information", section_style),
    ]

    report_info_rows = [
        [
            _make_paragraph("Report Title", table_body_style),
            _make_paragraph(REPORT_TITLE, table_body_style),
        ],
        [
            _make_paragraph("Scan Reference ID", table_body_style),
            _make_paragraph(scan_reference_text, table_body_style),
        ],
        [
            _make_paragraph("Cloud Provider", table_body_style),
            _make_paragraph(provider, table_body_style),
        ],
        [
            _make_paragraph("Cloud Account", table_body_style),
            _make_paragraph(account_name, table_body_style),
        ],
        [
            _make_paragraph("Requested By", table_body_style),
            _make_paragraph(
                f"{requested_by_name} ({requested_by_email})", table_body_style
            ),
        ],
        [
            _make_paragraph("Total Findings", table_body_style),
            _make_paragraph(str(total_findings), table_body_style),
        ],
        [
            _make_paragraph("Regions Scanned", table_body_style),
            _make_paragraph(scan_regions_text, table_body_style),
        ],
        [
            _make_paragraph("Scan Date", table_body_style),
            _make_paragraph(scan_date_text, table_body_style),
        ],
        [
            _make_paragraph("Report Generated", table_body_style),
            _make_paragraph(generation_date_text, table_body_style),
        ],
        [
            _make_paragraph("Compliance Observations", table_body_style),
            _make_paragraph(compliance_notes[0], table_body_style),
        ],
    ]

    info_table = Table(
        report_info_rows, hAlign="LEFT", colWidths=[1.75 * inch, 5.85 * inch]
    )
    info_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), THEME_LIGHT),
                ("TEXTCOLOR", (0, 0), (0, -1), THEME_BLUE),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#D6E2F0")),
                ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#D6E2F0")),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    flowables.append(info_table)
    flowables.append(Spacer(1, 12))

    flowables.append(Paragraph("Executive Summary", section_style))
    flowables.append(
        Paragraph(
            f"This report summarizes the findings produced by the DPDP Cloud Auditor after scanning the selected cloud environment. "
            f"The scan identified {total_findings} findings in total.",
            body_style,
        )
    )
    # flowables.append(
    #     Paragraph(
    #         f"Severity distribution: {severity_counts['CRITICAL']} critical, {severity_counts['HIGH']} high, "
    #         f"{severity_counts['MEDIUM']} medium, and {severity_counts['LOW']} low findings.",
    #         body_style,
    #     )
    # )
    if (
        compliance_notes
        and compliance_notes[0]
        != "No explicit compliance-related warning was generated by the current rule set."
    ):
        flowables.append(
            Paragraph(
                "Compliance-oriented checks also highlighted resources that may require additional review for data residency and sensitive-data handling.",
                body_style,
            )
        )
    flowables.append(Spacer(1, 6))

    flowables.append(Paragraph("Severity Summary", section_style))
    severity_rows = [
        [
            _make_paragraph("Severity", table_header_style),
            _make_paragraph("Count", table_header_style),
        ]
    ]
    for key, label in SEVERITY_ORDER:
        severity_rows.append(
            [
                _make_paragraph(label, table_body_style),
                _make_paragraph(str(severity_counts[key]), table_body_style),
            ]
        )

    summary_table = Table(
        severity_rows, colWidths=[2.1 * inch, 1.0 * inch], hAlign="LEFT"
    )
    summary_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), THEME_BLUE),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("ALIGN", (0, 0), (-1, 0), "CENTER"),
                ("ALIGN", (1, 1), (-1, -1), "CENTER"),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#B8C7D9")),
                ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#B8C7D9")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, ROW_LIGHT]),
            ]
        )
    )
    flowables.append(summary_table)

    chart = _build_severity_chart(severity_counts)
    if chart:
        flowables.append(Spacer(1, 8))
        flowables.append(Paragraph("Severity Distribution Chart", section_style))
        flowables.append(chart)
        flowables.append(Spacer(1, 8))

    flowables.append(Paragraph("Compliance Observations", section_style))
    for idx, note in enumerate(compliance_notes, start=1):
        flowables.append(Paragraph(f"{idx}. {note}", body_style))

    flowables.append(Paragraph("Detailed Findings", section_style))

    detail_headers = [
        "Resource ID",
        "Service",
        "Region",
        "Severity",
        "Issue Title",
        "Description",
        "Remediation",
    ]
    detail_data = [
        [_make_paragraph(header, table_header_style) for header in detail_headers]
    ]
    detail_severities = []

    if not findings_list:
        detail_data.append(
            [_make_paragraph("No findings available", table_body_style)]
            + [""] * (len(detail_headers) - 1)
        )
    else:
        for finding in findings_list:
            resource_id = finding.resource_id or "N/A"
            service = getattr(finding, "resource_type", "N/A")
            finding_job = getattr(finding, "scan_job", None)
            region = getattr(finding, "region", None)
            if not region and finding_job:
                region = getattr(finding_job, "target_regions_text", lambda: "N/A")()
            region_display = region or "N/A"
            severity = getattr(finding, "severity", "N/A").upper()
            issue_title = getattr(finding, "issue_type", "N/A")
            description = getattr(finding, "description", "N/A")
            remediation = getattr(finding, "recommendation", "N/A")

            detail_severities.append(severity)
            detail_data.append(
                [
                    _make_paragraph(resource_id, table_body_style),
                    _make_paragraph(service, table_body_style),
                    _make_paragraph(region_display, table_body_style),
                    _make_paragraph(severity.title(), table_body_style),
                    _make_paragraph(issue_title, table_body_style),
                    _make_paragraph(description, table_body_style),
                    _make_paragraph(remediation, table_body_style),
                ]
            )

    detail_table = Table(
        detail_data,
        repeatRows=1,
        splitByRow=1,
        colWidths=[
            1.0 * inch,
            0.8 * inch,
            0.7 * inch,
            0.7 * inch,
            1.15 * inch,
            1.65 * inch,
            1.6 * inch,
        ],
    )

    detail_style = TableStyle(
        [
            ("BACKGROUND", (0, 0), (-1, 0), THEME_BLUE),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#B8C7D9")),
            ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#D9E2EC")),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]
    )

    if not findings_list:
        detail_style.add("SPAN", (0, 1), (-1, 1))
        detail_style.add("ALIGN", (0, 1), (-1, 1), "CENTER")
        detail_style.add("BACKGROUND", (0, 1), (-1, 1), ROW_LIGHT)
    else:
        for row_index, severity in enumerate(detail_severities, start=1):
            row_bg = colors.white if row_index % 2 else ROW_LIGHT
            detail_style.add("BACKGROUND", (0, row_index), (-1, row_index), row_bg)
            detail_style.add(
                "BACKGROUND",
                (3, row_index),
                (3, row_index),
                SEVERITY_COLOR_MAP.get(severity, colors.white),
            )
            detail_style.add(
                "TEXTCOLOR",
                (3, row_index),
                (3, row_index),
                SEVERITY_TEXT_COLOR.get(severity, TEXT_DARK),
            )
            detail_style.add(
                "FONTNAME", (3, row_index), (3, row_index), "Helvetica-Bold"
            )
            detail_style.add("ALIGN", (3, row_index), (3, row_index), "CENTER")

    detail_table.setStyle(detail_style)
    flowables.append(detail_table)

    flowables.append(Spacer(1, 10))
    flowables.append(
        Paragraph(
            f"Report generated by {REPORT_NAME} on {generation_date_text}.",
            body_style,
        )
    )

    if scan_logs:
        flowables.append(Spacer(1, 16))
        flowables.append(Paragraph("Scan Activity Log", section_style))

        log_headers = ["Timestamp", "Level", "Message"]
        log_rows = [
            [_make_paragraph(header, table_header_style) for header in log_headers]
        ]

        for log in scan_logs:
            timestamp = _format_datetime(getattr(log, "created_at", None))
            level = getattr(log, "level", "N/A")
            message = getattr(log, "message", "N/A")
            log_rows.append(
                [
                    _make_paragraph(timestamp, table_body_style),
                    _make_paragraph(level.title(), table_body_style),
                    _make_paragraph(message, table_body_style),
                ]
            )

        log_table = Table(
            log_rows,
            repeatRows=1,
            splitByRow=1,
            colWidths=[1.4 * inch, 0.8 * inch, 5.4 * inch],
        )
        log_style = TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), THEME_BLUE),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#B8C7D9")),
                ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#D9E2EC")),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )

        for row_index in range(1, len(log_rows)):
            log_style.add(
                "BACKGROUND",
                (0, row_index),
                (-1, row_index),
                colors.white if row_index % 2 else ROW_LIGHT,
            )

        log_table.setStyle(log_style)
        flowables.append(log_table)

    doc.build(flowables, onFirstPage=_draw_pdf_page, onLaterPages=_draw_pdf_page)
    buffer.seek(0)
    return buffer


def generate_excel_report(
    findings: Iterable,
    report_context: dict,
    requested_by,
    scan_logs: Optional[Sequence] = None,
) -> io.BytesIO:
    findings_list = list(findings)
    generation_date = timezone.now()
    generation_date_text = _format_datetime(generation_date)

    scan_job = report_context.get("scan_job")
    scan_jobs = report_context.get("scan_jobs") or ([scan_job] if scan_job else [])
    scan_jobs = [job for job in scan_jobs if job]

    total_findings = len(findings_list)
    scan_date_text = _format_scan_date_range(scan_jobs)
    scan_reference_text = _format_scan_reference(scan_jobs)

    if requested_by:
        requested_by_name = requested_by.get_full_name() or getattr(
            requested_by, "username", "N/A"
        )
        requested_by_email = getattr(requested_by, "email", "n/a") or "n/a"
    else:
        requested_by_name = "N/A"
        requested_by_email = "n/a"

    cloud_account = report_context.get("cloud_account") or getattr(
        scan_job, "cloud_account", None
    )
    provider = cloud_account.get_provider_display() if cloud_account else "N/A"
    account_name = cloud_account.account_name if cloud_account else "N/A"

    scan_regions = report_context.get("scan_regions")
    regions_count = _count_regions(scan_regions)
    compliance_notes = _collect_compliance_observations(findings_list)

    workbook = Workbook()

    # Report Info Sheet
    metadata_sheet = workbook.active
    metadata_sheet.title = "Report Info"
    _write_excel_banner(
        metadata_sheet, f"{REPORT_NAME} - Report Information", "Report Metadata", 2
    )

    metadata_sheet.append(["Field", "Value"])
    for cell in metadata_sheet[3]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor=EXCEL_THEME_BLUE)
        cell.alignment = Alignment(
            horizontal="center", vertical="center", wrap_text=True
        )
        cell.border = THIN_BORDER

    metadata_entries = [
        ("Report Title", REPORT_TITLE),
        ("Scan Reference ID", scan_reference_text),
        ("Cloud Provider", provider),
        ("Cloud Account", account_name),
        ("Requested By", f"{requested_by_name} ({requested_by_email})"),
        ("Total Findings", str(total_findings)),
        (
            "Regions Scanned",
            f"{regions_count} regions selected" if regions_count else "N/A",
        ),
        ("Scan Date", scan_date_text),
        ("Report Generated", generation_date_text),
        ("Compliance Observations", compliance_notes[0]),
    ]

    for label, value in metadata_entries:
        metadata_sheet.append([label, value])

    for row in metadata_sheet.iter_rows(
        min_row=4, max_row=metadata_sheet.max_row, min_col=1, max_col=2
    ):
        for cell in row:
            cell.alignment = Alignment(wrap_text=True, vertical="top")
            cell.border = THIN_BORDER
        row[0].font = Font(bold=True, color=EXCEL_THEME_BLUE)
        row[0].fill = PatternFill("solid", fgColor="EAF2F8")
        row[1].fill = PatternFill("solid", fgColor="FFFFFF")

    metadata_sheet.freeze_panes = "A4"
    metadata_sheet.auto_filter.ref = f"A3:B{metadata_sheet.max_row}"
    metadata_sheet.page_setup.orientation = "portrait"
    _auto_size_columns(metadata_sheet, start_row=3, min_width=14, max_width=60)

    # Findings Sheet
    data_sheet = workbook.create_sheet(title="Scan Findings")
    _write_excel_banner(
        data_sheet,
        f"{REPORT_NAME} - Detailed Findings",
        "Vulnerability and Compliance Results",
        8,
    )

    headers = [
        "Resource ID",
        "Service",
        "Region",
        "Severity",
        "Issue Title",
        "Description",
        "Remediation",
        "Scan Date",
    ]
    data_sheet.append(headers)

    for cell in data_sheet[3]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor="1F4E79")
        cell.alignment = Alignment(
            horizontal="center", vertical="center", wrap_text=True
        )
        cell.border = THIN_BORDER

    for finding in findings_list:
        resource_id = finding.resource_id or "N/A"
        service = getattr(finding, "resource_type", "N/A")
        job = getattr(finding, "scan_job", None)
        region = getattr(finding, "region", None)
        if not region and job:
            region = getattr(job, "target_regions_text", lambda: "N/A")()
        region_display = region or "N/A"
        severity = getattr(finding, "severity", "N/A").title()
        issue_title = getattr(finding, "issue_type", "N/A")
        description = getattr(finding, "description", "N/A")
        remediation = getattr(finding, "recommendation", "N/A")
        scan_date_value = getattr(finding, "created_at", None)
        scan_date_value_text = (
            scan_date_value.strftime("%Y-%m-%d %H:%M:%S") if scan_date_value else "N/A"
        )

        data_sheet.append(
            [
                resource_id,
                service,
                region_display,
                severity,
                issue_title,
                description,
                remediation,
                scan_date_value_text,
            ]
        )

        current_row = data_sheet.max_row
        severity_fill = PatternFill(
            start_color=EXCEL_SEVERITY_COLOR.get(severity.upper(), "FFFFFF"),
            end_color=EXCEL_SEVERITY_COLOR.get(severity.upper(), "FFFFFF"),
            fill_type="solid",
        )
        data_sheet.cell(row=current_row, column=4).fill = severity_fill
        data_sheet.cell(row=current_row, column=4).font = Font(
            bold=True, color="1F2937"
        )
        data_sheet.cell(row=current_row, column=4).alignment = Alignment(
            horizontal="center", vertical="top", wrap_text=True
        )

    for row in data_sheet.iter_rows(
        min_row=4, max_row=data_sheet.max_row, min_col=1, max_col=8
    ):
        for cell in row:
            cell.border = THIN_BORDER
            cell.alignment = Alignment(wrap_text=True, vertical="top")

        for cell in row:
            if cell.row % 2 == 0:
                if cell.column != 4:
                    cell.fill = PatternFill("solid", fgColor="F8FAFC")

    data_sheet.freeze_panes = "A4"
    data_sheet.auto_filter.ref = f"A3:H{data_sheet.max_row}"
    data_sheet.page_setup.orientation = "landscape"
    data_sheet.page_setup.fitToWidth = 1
    data_sheet.page_setup.fitToHeight = 0
    _auto_size_columns(data_sheet, start_row=3, min_width=12, max_width=55)

    # Logs Sheet
    if scan_logs:
        logs_sheet = workbook.create_sheet(title="Scan Logs")
        _write_excel_banner(
            logs_sheet,
            f"{REPORT_NAME} - Scan Activity Log",
            "System Events and Scan Messages",
            3,
        )

        logs_sheet.append(["Timestamp", "Level", "Message"])
        for cell in logs_sheet[3]:
            cell.font = Font(bold=True, color="FFFFFF")
            cell.fill = PatternFill("solid", fgColor="1F4E79")
            cell.alignment = Alignment(
                horizontal="center", vertical="center", wrap_text=True
            )
            cell.border = THIN_BORDER

        for log in scan_logs:
            timestamp = _format_datetime(getattr(log, "created_at", None))
            level = getattr(log, "level", "N/A")
            message = getattr(log, "message", "N/A")
            logs_sheet.append([timestamp, level.title(), message])

        for row in logs_sheet.iter_rows(
            min_row=4, max_row=logs_sheet.max_row, min_col=1, max_col=3
        ):
            for cell in row:
                cell.border = THIN_BORDER
                cell.alignment = Alignment(wrap_text=True, vertical="top")
            if row[0].row % 2 == 0:
                for cell in row:
                    cell.fill = PatternFill("solid", fgColor="F8FAFC")

        logs_sheet.freeze_panes = "A4"
        logs_sheet.auto_filter.ref = f"A3:C{logs_sheet.max_row}"
        logs_sheet.page_setup.orientation = "landscape"
        logs_sheet.page_setup.fitToWidth = 1
        logs_sheet.page_setup.fitToHeight = 0
        _auto_size_columns(logs_sheet, start_row=3, min_width=14, max_width=60)

    output = io.BytesIO()
    workbook.save(output)
    output.seek(0)
    return output
