# Generated by Django 6.0.3 on 2026-03-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0002_scanjoblog"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanjob",
            name="cancel_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="scanjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("INTERRUPTED", "Interrupted"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
