# Generated by Django 6.0.3 on 2026-03-17 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scanner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=100)),
                ("check_id", models.CharField(max_length=100)),
                ("check_title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("WARNING", "Warning"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField()),
                ("recommendation", models.TextField()),
                ("raw_result", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scan_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_results",
                        to="scanner.scanjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["scan_job"], name="report_scan_scan_jo_b1e73f_idx"
                    ),
                    models.Index(
                        fields=["status"], name="report_scan_status_0a8bcf_idx"
                    ),
                    models.Index(
                        fields=["severity"], name="report_scan_severit_6b4aeb_idx"
                    ),
                ],
            },
        ),
    ]
