# Generated by Django 6.0.3 on 2026-03-23 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cloudaccount",
            name="access_key",
        ),
        migrations.RemoveField(
            model_name="cloudaccount",
            name="account_id",
        ),
        migrations.RemoveField(
            model_name="cloudaccount",
            name="region",
        ),
        migrations.RemoveField(
            model_name="cloudaccount",
            name="secret_key",
        ),
        migrations.AddField(
            model_name="cloudaccount",
            name="credentials",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CloudRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region_name", models.CharField(max_length=50)),
                (
                    "cloud_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regions",
                        to="accounts.cloudaccount",
                    ),
                ),
            ],
        ),
    ]
