# Generated by Django 6.0.3 on 2026-05-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_cloudaccount_access_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudaccount",
            name="account_id",
            field=models.CharField(default="", max_length=100),
        ),
    ]
