# Generated by Django 6.0.3 on 2026-05-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_cloudaccount_account_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloudaccount",
            name="account_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
