# Generated by Django 6.0.3 on 2026-05-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_cloudaccount_account_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudaccount",
            name="credentials_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
